# Configuration for SilkTouchSpawners plugin

# The lore that is required on a pickaxe to break a spawner if Silk Touch is not present.
required-lore: "Special Lore"

# The format for the name of the spawner item when it is dropped.
# Use {mobtype} as a placeholder for the mob type.
spawner-name: "&FF4500{mobtype} &FFFFFFSpawner"

# Lore for the spawner item when it is dropped.
spawner-lore:
  - ""
  - "&FFFFFFSpawner type: &FF4500{mobtype}"
  - ""

# Messages displayed to the player
messages:
  # Message displayed when the player does not have permission to break the spawner.
  no-permission-break-spawner: "&DC143CYou do not have permission to break this spawner."
  # Warning message displayed when the player tries to break the spawner without permission or Silk Touch.
  no-permission-warning: "&DC143CIf you try to break it again without the proper requirements, the spawner will be broken and not dropped."
  # Message displayed when the spawner is successfully broken.
  spawner-break-success: "&FFFFFFYou successfully mined a &FF4500{mobtype} &FFFFFFSpawner!"
  # Message displayed when the spawner is dropped instead of being added to the player's inventory.
  spawner-drop-message: "&cYour inventory is full. The spawner has been dropped on the ground."
  # Message displayed when the spawner is broken without dropping.
  spawner-break-failure: "&DC143CThe spawner was broken and not dropped because you didn't have the proper requirements."

# Global setting to allow or disallow changing spawners with mob eggs.
# If set to true, players can change spawners with mob eggs.
# If set to false, only players with the silktouchspawners.changespawner permission can change spawners.
allow-changing-spawners-with-mob-eggs-globally: false

# Option to control if spawners should be added to the player's inventory or dropped on the ground when mined.
spawner-to-inventory-on-drop: true

# Custom items configuration
custom-items:
  special_pickaxe:
    itemtype: "DIAMOND_PICKAXE"
    name: "&bSpecial Pickaxe"
    lore:
      - "&7This pickaxe has special powers."
    enchants:
      efficiency: 5
      unbreaking: 3
    custommodeldata: 12345
  epic_sword:
    itemtype: "IRON_SWORD"
    name: "&cEpic Sword"
    lore:
      - "&7This sword can defeat any foe."
    enchants:
      sharpness: 5
      fire_aspect: 2
    custommodeldata: 67890